
import flet as ft

# 1 урок
less_1 = ft.Container(
    ft.Column(controls=[
        # ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Начало',text_align='center'),width=700),
        ft.Container(ft.Text('Ты прошел уроки по роблоксу и вот новый уровень - разработка игр в Майнкрафте на питоне. Поздравляем! Стоит понимать, что прежде всего, мы будем изучать питон. Майнкрафт - это среда, где код будет исполняться и мы сможем делать разные крутые штуки. Как и всегда, начнем с чего-то простого, и в конце научимся делать дейтсвительно сложные вещи в майнкрафте. Можно будет даже поднять свой сервер с модами и играть на нём вместе с друзьями.'),width=700),
        ft.Container(ft.Text('Начнём. Нам нужно связать питон и майнкрафт. Сделаем это через запуск сервера Spigot. На рабочем столе найди папку - Minecraft Tools, зайди в нее. Запусти файл - Start_Server. На экране появится консоль с букафками.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/1.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Сервер заупстится через 15 секунд. Вначале процесса запуска увидите строку с версией майнкрафта, которую запускает сервер.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/2.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Именно эту версию и нужно будет выбрать (или установить) в тлаунчере. Не закрываем окно с консолью! Оно в фоновом режиме держит сервер на компьютере. Заходите в тлаунчер, выбираете нужную версию и запускаете игру'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/3.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('После запуска игры заходим в сетевую игру и нажимаем "Добавить". Название сервера пишем любое, например - Питон. Адрес сервера - localhost, и нажимаем готово. В списке серверов снизу появится наш сервер. По умолчанию он бдует активен с игроками - 0/20. Заходим на сервер.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/4.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/5.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Отлично, сервер накатили, майнкрафт к нему подключили. Теперь нужно подключить среду разработки, где и будем писать код. Для начала создайте папку на рабочем столе со своей фамилией и именем. Кликните по ней правой кнопкой мыши и выбирете - открыть с помощью Code.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/6.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Откроется окно VS Code. Vs Code - это место, где можно удобно писать код.'),width=700),
        ft.Container(ft.Text('Все файлы нужно хранить удобным образом, не перемешивать код из разных уроков. Поэтому сразу делаем красиво - слева, под проводником, в пустом месте кликнете правой кнопкой мыши и выбирете - создать папку'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/7.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Папку назовите - lesson_1. Здесь будут храниться файлы первого урока. '),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/8.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Теперь кликни по созданной папке правой кнопкой мыши и выбери - создать файл. '),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/9.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Введи название - 1.py и нажми enter. И это не РУ на русском, это пай - py на аглийском. Сокращение от python.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/10.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Отлично! Здесь мы и будем пистаь код. Напишем простую программу телепортации. Зайдите обратно в майнкрафт и нажмите F3, чтобы узнать координаты. '),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/11.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Запомните эти координаты или запишите. Далее отбегите подальше. '),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/12.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Перепишите себе код. Слово в слово. Буква в букву. По опыту роблокса вы уже понимаете, что если ошибёшься и поставишь в одном слове вместо большой буквы - маленькую, то вся программа не будет работать. Поэтому всегда будьте внимательны.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/13.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Запустите программу. Для этого нажмите на треуголькиик справа сверху.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/14.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Снизу вскода откроется консоль. Если ошибок в коде нет, то обновится строка с расположением файла и все.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/15.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Зайдите в майнкрафт. Персонаа должно было тепнуть в заданные координаты.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/16.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Специально допущу ошибку, уберу скобки во второй строке у create и запущу программу. Поулчаю ругательства в косноли.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/17.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Разбираться в этих ругательствах - отдельное искусство, которому нужно будет учиться. Иногда там написаны понятные вещи, которые позволяют быстро найти ошибку. В другой раз - это просто ругательства. Будем разбираться в процессе.'),width=700),
        ft.Container(ft.Text('У тебя получилось? Поздравляю! Ты поднял сервер, связал его с майнкрафтом, подключил среду разработки и написал первую программу - телепортацию персонажа. Разбираться в коде мы сейчас не будем, цель была не в этом. Разберемся в следующих уроках.'),width=700),
        ft.Container(ft.Text('Скажи преподавателю - я молодец, сделал первый урок. Он разрешит перейти к следующему.'),width=700),
        ft.Container(ft.Text(''),width=700),
        
        ])
)

# 2 урок
less_2 = ft.Container(
    ft.Column(controls=[
        # ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Тепаем хомяка.',text_align='center'),width=700),
        ft.Container(ft.Text('В уроке будем разбираться с телепортацией и начнем знакомиться с языком программирования Питон.'),width=700),
        ft.Container(ft.Text('Самое простое, что можем быть в любом языке программирования - это переменные.'),width=700),
        ft.Container(ft.Text('Переменные нужны для хранения данных, которые позже будут использованы в программе. Данные — это любая полезная информация: числа, имена, текст, списки значений и т. д. К примеру, в переменной pickaxes может храниться число 12. Создайте папку - lesson_2, в ней файл - 2.py . В файле напишите код.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/1.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Это всё, что нужно, чтобы создать переменную и дать ей како-то значение'),width=700),
        ft.Container(ft.Text('Чтобы создать переменную в Python, нужно ввести в окне консоли имя переменной, поставить знак «равно» (=), а после добавить значение этой переменной. Допустим, вы решили отправить игрока в путешествие по биомам. В этом случае ему понадобятся солидные запасы провизии. Назовем переменную bread и зададим ей значение 145:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/2.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Имя переменной всегда пишется слева от  знака «равно», а  значение, которое в  ней хранится,  — справа. Эта строка кода означает, что мы объявили переменную bread и присвоили ей значение 145.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/3.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Объявив переменную и присвоив ей значение, вы можете проверить, что в  ней хранится. Для печати чего-либо в консоли, используем print(). Перепишите следующий код и запустите.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/4.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('В консоли распечатается значение перменной bread'),width=700),
        ft.Container(ft.Text('Вы можете называть переменные как угодно, однако желательно, чтобы имя соответствовало назначению переменной. Так будет проще понять, что происходит в вашей программе. Имена переменных пишутся со  строчной буквы. Это не  правило языка, а  соглашение, принятое Python-программистами. Ему нужно следовать, чтобы другим программистам было удобно читать ваш код.'),width=700),
        ft.Container(ft.Text('Как устроены языки программирования',text_align='center'),width=700),
        ft.Container(ft.Text('У каждого языка программирования есть набор правил — синтаксис. Эти правила похожи на правила русского языка, которыми мы пользуемся, чтобы составлять предложения. Если вы будете знать синтаксис языка Python, ваши программы будут работать, а если нарушите их, компьютер просто не поймет, что вы от него хотите.'),width=700),
        ft.Container(ft.Text('Каждая инструкция в  вашем коде похожа на  предложение. Только в  русском языке конец предложения обозначается точкой, а в Python — переходом на новую строку. Строка с инструкцией называется командой.'),width=700),
        ft.Container(ft.Text('Предположим, вы решили вести учет кирок (pickaxes), блоков железной руды (iron ore) и булыжников (cobblestone). Для этого можно ввести следующее:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/5.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Название блоков железной руды для простоты я сократил до одного слова. Обратите внимание, что каждый тип предметов записан отдельной строкой. Благодаря этому Python понимает, что вы хотите отслеживать количество трех разных предметов. Если вы запишете все команды в одну строку, Python запутается и сообщит о синтаксической ошибке:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/6.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Синтаксическая ошибка (SyntaxError) означает, что Python не понимает ваших команд и не может их выполнить. В данном случае программе неясно, где начинается и где заканчивается каждая команда. Такая ошибка называется «неверный синтаксис» (invalid syntax).'),width=700),
        ft.Container(ft.Text('Также Python не поймет, что нужно делать, если в начале строки будет стоять пробел'),width=700),
        ft.Container(ft.Text('Синтаксис для переменных',text_align='center'),width=700),
        ft.Container(ft.Text('Имена, которые вы будете давать переменным, тоже должны подчиняться синтаксису языка Python. Имейте в виду:'),width=700),
        ft.Container(ft.Text('В имени не должно быть других символов, кроме латинских букв, цифр и нижнего подчеркивания (_).'),width=700),
        ft.Container(ft.Text('Не начинайте имя с цифры. 9bread не подойдет. Однако в любом другом месте цифра стоять может — например, здесь: bread9.'),width=700),
        ft.Container(ft.Text('До и  после знака «равно» лучше ставить пробел. Это не  обязательно, но  так принято делать в  среде программистов, чтобы легче читать код.'),width=700),
        ft.Container(ft.Text('Телепортация игрока',text_align='center'),width=700),
        ft.Container(ft.Text('Вы научитесь использовать переменные и работать с целыми числами, создав программу телепортации игрока.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/7.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('На рисунке видно, что позиция игрока в мире Minecraft определяется тремя координатами: x («икс»), y («игрек») и z («зэт»). Координата y соответствует высоте, x и z — положению на горизонтальной плоскости.'),width=700),
        ft.Container(ft.Text('Начнем писать код телепортации и разберемся в нем '),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/8.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Эти команды нужны для подключения к игре Minecraft, и они должны быть в каждой Python-программе, которая с ней взаимодействует. '),width=700),
        ft.Container(ft.Text('mc = Minecraft.create() - создает соединение с майнкрафтом. При этом адрес и порт будут по умолчанию, а это локалхост, который вы вводите при подключению к серверу. Он же - 127.0.0.1.'),width=700),
        ft.Container(ft.Text('from mcpi.minecraft import Minecraft - подключаем библиотеку для работы с майнкрафтом через питон. Она под капотом и позволяет нам пистаь код, который отрабатывает сервер.'),width=700),
        ft.Container(ft.Text('Затем объявим три целочисленные переменные с именами x, y и z.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/9.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Эти переменные соответствуют координатам, в которые вы собираетесь телепортировать игрока. Пока присвоим им значения 10, 110 и 12. Далее введите следующую строку кода — она и будет телепортировать игрока:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/10.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Выражение setTilePos() — это функция, то  есть фрагмент ранее созданного программистами кода. Функция setTilePos(x, y, z) дает игре команду изменить координаты игрока на  значения, указанные в скобках'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/11.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Запустите код и перейдите в майнкрафт. Убедитесь, что игрока тепнуло.'),width=700),
        ft.Container(ft.Text('Замедление телепортации',text_align='center'),width=700),
        ft.Container(ft.Text('Python выполняет команды кода почти мгновенно. Однако вы можете замедлить процесс, научив вашу программу делать паузу в несколько секунд. Воспользуйтесь модулем time, который содержит готовые функции для работы со временем. Для этого добавьте в самый верх программы следующую строку:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/12.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Важно помнить, что модуль time должен быть импортирован (с помощью команды import) раньше всех его функций. Например, функции sleep(), которая позволяет приостановить выполнение программы на указанное число секунд. В противном случае Python не сможет найти функцию sleep() и, не зная, что делать дальше, остановит вашу программу. Именно поэтому команды импорта всех необходимых вам модулей лучше помещать в начале кода.'),width=700),
        ft.Container(ft.Text('Сделаем задержку в телепортации. Добавтье строку в код'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/13.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Она позволит сделать задержку перед телепортацией. Запустите, зайдите в программу и посмотрите результат.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_2/14.gif',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Отлично. Теперь сделай задание - тебя должно тепать каждые 3 секунды в разные координаты 5 раз подряд. Сделай это и покажи преподу. Он оценит и разрешит перейти к следующему заданию.'),width=700),
        ft.Container(ft.Text(''),width=700),
        
        
        ])
)
# 3 урок
less_3 = ft.Container(
    ft.Column(controls=[
        # ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_1/',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Супер стройка',text_align='center'),width=700),
        ft.Container(ft.Text('Для начала разберемся с выражениями'),width=700),
        ft.Container(ft.Text('Объединив числа, переменные и математические операции, вы можете создать небольшой фрагмент кода — выражение. Например, такое: 2 + 2. Из выражений можно составлять команды'),width=700),
        ft.Container(ft.Text('Команда — это фрагмент кода, занимающий одну или несколько строк и выполняющий в программе определенные действия. Так, выражение 2 + 2 может быть частью команды zombies = 2 + 2.'),width=700),
        ft.Container(ft.Text('Напишите выражение и посмотрите, что получится. Не забудьте создать папку lesson_3 и в ней 3.py. Напоминать вам об этом дальше не буду. Переходя на новый урок каждый раз создавайте под него папку и питон файл в ней.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/1.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Запустив эту программу, вы увидите число 4.'),width=700),
        ft.Container(ft.Text('Операции',text_align='center'),width=700),
        ft.Container(ft.Text('В математике операциями называются производимые над числами действия. В программировании математические операции позволяют изменять и объединять числа нужным образом.'),width=700),
        ft.Container(ft.Text('В Python есть все основные математические операции: сложение, вычитание, умножение и деление, — а также более сложные, такие как возведение в степень. Начнем со сложения.'),width=700),
        ft.Container(ft.Text('Построим что-нибудь',text_align='center'),width=700),
        ft.Container(ft.Text('С помощью функции setBlock() в мире Minecraft можно создать блок и поместить его в заданное место. Аналогично setPos() и setTilePos() функция setBlock() принимает значения трех аргументов — координат x, y и z. Но есть у нее и четвертый аргумент: тип блока. Он определяет, какой именно блок нужно добавить в игру.'),width=700),
        ft.Container(ft.Text('Каждому типу блоков, будь то трава, лава или арбуз, соответствует определенное целое число. Для стоячей лавы это 11, для воздуха — 0, для воды — 8, а для арбуза — 103.'),width=700),
        ft.Container(ft.Text('Ниже представлены коды всех блоков'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/2.jpg',width=500),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/3.jpg',width=500),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/4.jpg',width=500),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/5.jpg',width=500),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/6.jpg',width=500),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/7.jpg',width=500),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Зайдите в майнкрафт, посмотрите координаты игрока. Напишите следующий код, вставив координату блока перед игроком. (координаты в примере будут отличаться от ваших! Вычислите их самостоятельно)'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/9.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Запустите и зайдите в майнкрафт. перед вами должен появиться арбуз.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_3/8.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Задание - сделайте портал в ад из обсидиана с помощью кода. Покажите преподу, когда будет готово.'),width=700),
        ft.Container(ft.Text(''),width=700),
        ])
)
# 4 урок
less_4 = ft.Container(
    ft.Column(controls=[
        # ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_4/1.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Строим и балуемся',text_align='center'),width=700),
        ft.Container(ft.Text('Вначале узнаем текущую позицию игрока. Для этого вызовите функцию getTilePos()'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_4/1.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Зная координаты под ногами, можно пошалить.'),width=700),
        ft.Container(ft.Text('Добавьте блок лавы под ноги персонажу. Покажи преподу результат.'),width=700),
        ft.Container(ft.Text('Теперь сделаем что-то дейтсивтельно прикольное. Из роблокса ты уже знаешь, как делать бесконечные циклы. Здесь они делаются похожим образом.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_4/2.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('while True - создает бескоечный цикл. Не забудьте поставить задержку внутри цикла в секунду или рядом. Если попробовать вывыести принт в бесконечном икле без задержки, то процессор встанет секунд через 5. А может и нет. От компьюера зависит.'),width=700),
        ft.Container(ft.Text('Так вот получай позицию игрока в бесконечном цикле, и через каждые 0.2 секунды создавай под ним блок чего-нибудь. Получится интересный эффект - персонаж идет, и по его маршруту тянется созданный блок. Сделай задание и покажи преподу.'),width=700),
        ft.Container(ft.Text('Сделали задание? Отлично! Теперь научимся строить быстро, качественно, недорого.'),width=700),
        ft.Container(ft.Text('Для установки единичного блока мы использовали функцию setBlock(), однако есть еще одна функция — setBlocks(). Она позволяет создать прямоугольный параллелепипед, который еще называют кубоидом, состоящий сразу из нескольких блоков. При этом длина, ширина и высота кубоида могут быть разными.'),width=700),
        ft.Container(ft.Text('Функция setBlocks() позволяет заполнять блоками большие объемы пространства. Вызвав эту функцию, передайте ей два набора координат и тип блока. Первый набор координат должен соответствовать положению одного угла кубоида, а  второй  — положению противоположного ему угла'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_4/3.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Давайте что-нибудь построим. Перепишите код и запустите.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_4/4.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_4/5.gif',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Отлично! Сделали кучу камня. Как сделать внутри постоту? Да просто добавить там материал-воздух. '),width=700),
        ft.Container(ft.Text('Задание - сделать будку для собаки 50х6х50 блоков из любого материала. Постройте дом с помощью кода. Функция setBlocks() вам в помощь.'),width=700),
        ft.Container(ft.Text(''),width=700),
        
        ])
)
# 5 урок
less_5 = ft.Container(
    ft.Column(controls=[
        ft.Container(ft.Text('Переписка',text_align='center'),width=700),
        ft.Container(ft.Text('В этом уроке вам предстоит познакомиться с еще одним типом данных — строками. В строках обычно содержатся буквы и знаки, но  могут быть и  числа. Строки  — важная часть Python-программ. С их помощью вы можете вывести на экран сообщение, чтобы донести до пользователя нужную информацию.'),width=700),
        ft.Container(ft.Text('Строковый тип данных позволяет работать с  текстовой информацией разного вида: от буквы и знака, таких как «a» или «:», до целых абзацев. Каждая буква, цифра и знак в составе строки называется символом. Если вы хотите использовать в коде буквы, слова или предложения, строки — это именно то, что вам нужно. Содержимое строки заключается в кавычки-лапки. Вот так:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/1.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('А вот еще одна строка:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/2.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Заметили, чем отличается один пример от  другого? Первая фраза заключена в двойные кавычки , а вторая — в одинарные. В строках можно использовать оба вида кавычек. Однако смешивать их нельзя! Если строка начинается с одиночной кавычки, то и заканчиваться она должна одиночной кавычкой. И наоборот: если строка начинается с двойной кавычки, в конце тоже должна стоять двойная. Оба вида кавычек поддерживаются в Python неспроста. Если в тексте нужно выделить прямую речь, вы без проблем сможете использовать двойные кавычки, заключив строку в одинарные.'),width=700),
        ft.Container(ft.Text('Привет, мир Minecraft!',text_align='center'),width=700),
        ft.Container(ft.Text('Чтобы общаться с другими пользователями, вы можете отправлять сообщения в чат с помощью функции postToChat(). Эта функция принимает строковый аргумент, отображая его содержимое в окне игрового чата'),width=700),
        ft.Container(ft.Text('Напишите и запустите следующий код'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/3.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Получим такую красоту'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/4.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Проблема с кодировкой. Чем больше будете программировать, тем чаще будете с ней сталкиваться. Русский язык далего не везде сходу нормально отображается. Сейчас пока просто опустим эту проблему и попечатаем на английском.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/5.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Напоминаю, что аргумент  — это данные, которые вы передаете в функцию при ее вызове и  которые нужны ей для работы. В  предыдущей главе мы передавали в  функции числовые значения, однако postToChat() требуется аргумент-строка.'),width=700),
        ft.Container(ft.Text('Функция postToChat() похожа на print(). Обе выводят строки на экран, и обе могут принимать в качестве аргумента переменную, в которой хранится строка. Отличие их в том, что print() выводит строку в окне консоли Python, а postToChat() — в чате Minecraft.'),width=700),
        ft.Container(ft.Text('Задание - вернитесь к программе в уроке, где телепортировали перса по 5 координатам. После каждой телепортации, выведите координаты в чат. ПОкажи преподу работу программы, когда сделаешь.'),width=700),
        ft.Container(ft.Text('Отлично! Писать в чат мы научились. Теперь научимся получать сообщения из чата, которые вводит пользователь. Перепишите и запустите код'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/6.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Теперь зайдите в майнкрафт. Лучше сделать отображение в окне, чтобы было видно вскод и майнкрафт одновременно. Отправьте сообщение в чат. Оно же должно отобразиться и в консоли в вскоде.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/7.gif',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Мы получили чат из майнкрафта в коде. Отлично! Теперь мы можем что-то делать в ответ на команды.'),width=700),
        ft.Container(ft.Text('Сделаем следующее - если в чат написать lol, то тебе в ответ напишут - сам лол. Перепиши код и запусти'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/9.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_5/8.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Получилось? Хорошо! Задание - сделай тай, чтобы если в чат написать "Алмаз", то перед тобой возникал блок аламазов. Сделай и покажи преподу.'),width=700),
        ft.Container(ft.Text(''),width=700),
        ])
)
# 6 урок
less_6 = ft.Container(
    ft.Column(controls=[
        # ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Итоги 5 уроков. Что дальше?',text_align='center'),width=700),
        ft.Container(ft.Text('Давай в этом уроке просто поговрим. Ты уже научился делать что-то в майнкрафте на питоне. И на самом деле мы изучили всю основу библиотеки mcpi. На ней еще можно сделать несколько прикольных проектов,  но нужна она только дл яознакомления. Все команды, что в ней доступны мы изучили. Она умеет получать координаты игрока, телепортировать его, создавать блоки, определять тип блока по координатам и писать в чат. На этом всё. Больше данная библиотека ничего делать не умеет. На ней не написать полноценных модов. Не собрать интересный сервер. А ведь нам так этого хочется, правда! Собрать крутой сервер с персональными модами, прописать собственные скрипты, запустить сервер для друзей и админить его. Вышкой будет подключение сайта и продажа привелегий. Так можно зарабатывать на своём сервере майнкрафт. Вот этого хочется. И мы это сделаем. mcpi - это ясельки, первый шаг. Теперь же давай научимся создавать свой сервер на любой версии майнкрафта, а не только на версиях 15 летней давности, подключать к ней моды и управлять через rcon на питоне.'),width=700),
        ft.Container(ft.Text('Для работы мы использовали сервер в майнкрафте - spigot.'),width=700),
        ft.Container(ft.Text('Если прочитать определение спигота, то нам напишут:'),width=700),
        ft.Container(ft.Text('Spigot — глобальная серверная модификация, предоставляющая API для взаимодействия с игровым миром и созданная для упрощения создания плагинов к SMP-серверу. Spigot создан на основе ядра. CraftBukkit и призван заменить «старшего брата» стабильностью и производительностью. Кроме этого, почти все плагины, написанные для CraftBukkit, пойдут и на Spigot, но на Spigot написаны и собственные, недоступные CraftBukkit’у плагины.'),width=700),
        ft.Container(ft.Text('Что-то здесь понятно, что-то нет. Понятно, что спигот основан на ядре CraftBukkit, на нем можно писать и запускать моды и так далее. Почему мы используем спигот? Потому что это просто. Нужно настроить сервер, на это нужно время, но потом он запускается и поддерживается буквально одной кнопкой. Это и правда удобно.'),width=700),
        ft.Container(ft.Text('В первых 5 уроках вы использовали уже готовый сервер. Теперь же давайте научимся качать и настраивать его самостоятельно, чтобы вы могли повторить это и дома.'),width=700),
        ft.Container(ft.Text('Переходим на сайт - https://serverjar.org/download/spigot и качаем нужную версию сервера',selectable=True),width=700),
        ft.Container(ft.Text('В своей папке создаем папку - server. Закидываем в неё скаченный файл. Файл будем с расширением .jar - это расширение java. Скорее всего java у вас на кномпе будет установлена не той версии, либо вообще не установлена. '),width=700),
        ft.Container(ft.Text('Например, для последнией (на данный моменти) версии майнкрафта - 1.21.4, нужна версия джавы - jdk 23. Java качается на оф сайте оракла. Заходим на сайт по ссылке:'),width=700),
        ft.Container(ft.Text('https://www.oracle.com/java/technologies/javase/jdk23-archive-downloads.html',selectable=True),width=700),
        ft.Container(ft.Text('И находим exe установщик для винды, качаем и устанвливаем'),width=700),
        ft.Container(ft.Text('Однако вначале проверьте, может он уже установлен. Переходим на диск С, Program Filse, Java, там увидите установленные версии. Если нужная уже установлена, то качать не нужно. Если нет - качаем и устанавливаем'),width=700),
        ft.Container(ft.Text('Смотрим, может установлена'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/4.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Качаем на сайте'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/3.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('После установки, нажимаем на скаченный файл server.jar в папке server в вашей папке.'),width=700),
        ft.Container(ft.Text('Ждём несколько минут. Файлы сервера распакуются. Должно быть так:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/5.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Просто ждите, пока все папки и файлы, как на картинке выше, не распакуются.'),width=700),
        ft.Container(ft.Text('После этого нам нужно изменить несколько параметров. Первый - принять пользовательское соглашение. Для этого открываем файыл eula.txt и меняем eula=false на eula=true. Сохраняем и закрываем.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/6.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Снова нажимаем на server.jar и ждем. Через какое то время запустится серевер майнкрафта'),width=700),
        ft.Container(ft.Text('В папке добавится еще много разных файлов, а так же запустится окно сервера с консолью и нагрузкой на систему.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/7.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Отлично! Чтобы подключиться к серверу не хватает всего одной вещи - перевести режим работы в оффлайн. Для этого остановите сервер (просто закройте окно с консолью сервера) и откройте файл server.txt Здесь хранятся все настройки сервера. У меня он открывается в vscod, так же он может открыться в блокноте, как и eula.txt. Найдите строку online-mode=true и замените на online-mode=false, сохраните и запустите сервер.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/9.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Поздравляю! Сервер запущен. Он пустой, базовый, но уже работает. Теперь нужно проверить, что все подключается как надо. Заходите в майнкрафт на той же версии, что и сервер. И подключаетесь к localhost, как и в первом уроке. '),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/8.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/10.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Так же в консоли сервера мы видим, что подключен игрок - min и заспавнен по таким то координатам.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_6/11.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Готово! Вы создали сервер спигот нормальной, свежей версии и запустили его. Если у вас все получилось, можете переходить к следующему уроку. Преподу только не забудьте сказать, что я молодец и сделал урок. Чтобы он был в курсе, что ты молодец.'),width=700),
        ft.Container(ft.Text(''),width=700),
        ft.Container(ft.Text(''),width=700),
        ft.Container(ft.Text(''),width=700),
        
        
        ])
)
# 7 урок
less_7 = ft.Container(
    ft.Column(controls=[
        ft.Container(ft.Text('Подключаем моды',text_align='center'),width=700),
        ft.Container(ft.Text('Да, именно сегодня ты научишься подключать моды к своему собственному серверу майнкрафт. И это прекрасно. Написание собственных модов - дело непростое. И делается это чаще всего на джаве. Джава - непростой язык. Он напорядок сложнее питона и лезть в него сейчас мы точно не будем. Мы научимся создавать свой сервер на условно любой конфигруции в любом режиме, подключать нужные моды, управлять им и шарить сервер в интренет. Это план на следующие уроки. А к написанию собственных модов вернемся позже.'),width=700),
        ft.Container(ft.Text('Для начала стоит понять, что стандартный spigot строится на ядре ванилы. Ванила по умолчанию не поддерживает плагины. Нужна именно fork версия. Версия, спигота, что была скачана на прошлом уроке, у меня с модами не завелась. Что завелось, так это ядро спигот скаченное по ссылке:'),width=700),
        ft.Container(ft.Text('https://minecraft-mod.su/1030-spigot-1214.html',selectable=True),width=700),
        ft.Container(ft.Text('Однако на последних версиях игры большиснтво плагинов и модов может не завестить. Для стабильности рекомендуется понизить версию. Максимум стоит работать на версии 1.20.6. Её лучше всего скачать по ссылке :'),width=700),
        ft.Container(ft.Text('https://papermc.io/downloads/all',selectable=True),width=700),
        ft.Container(ft.Text('Здесь используется другой движок - paper. На момей практике он показал себя более стабильно. '),width=700),
        ft.Container(ft.Text('Если качается долго, попросите у препода на флешке. Скините и все.'),width=700),
        ft.Container(ft.Text('Создайте папку Server_2, закиньте в нее скачанный файл сервера. Ранее мы просто запускали файл jar, и он распаковывался. При этом иной раз он мог распаковываться минут 5. Хотелось бы получить какую-тио индикацию выполнения. Для этого создадим батник - файл консоли, который выполнит распаковку и покажет в процессе, что вообще происходит.'),width=700),
        ft.Container(ft.Text('Для этого в папке server_2 создайте start.bat файл. Откройте его в редакторе кода, в блокноте или vscod и вставьте тужа слеудющие строки:'),width=700),
        ft.Container(ft.Text('@ECHO OFF\ncd /d "%~dp0"\n"C:\Program Files\Java\jdk-23\bin\java.exe" -Xms2048M -Xmx4096M -jar server.jar',selectable=True),width=700),
        ft.Container(ft.Text('C:\Program Files\Java\jdk-23\bin\java.exe - это путь до установленной последней версии джавы. У вас он скорее всего такой, но может и отличаться.'),width=700),
        ft.Container(ft.Text('server.jar - название файла, который распаковываем. У вас он скорее всего называется по другому. Это то, что вы скачали из интернета и закинули в папку server_2. Переименуйте файл сервера на server. После этого запускайте start.bat. Получите что-то такое:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_7/4.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_7/5.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('После запуска вначале какое-то время качается нужная вресия ядра майнкрафта'),width=700),
        ft.Container(ft.Text('После в папке сервера появятся новые папки. Здесь снова нужно дать разрешение в eula.txt и переименовать offline-mode в файле server.txt, как и раньше. После запустить сревер удобнее через start.bat, который создали ранее. Запустите, подключитесь в майнкрафте и убедитесь, что все работает.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_7/6.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('После этого качаете свой первый плагин по ссылке:'),width=700),
        ft.Container(ft.Text('https://dev.bukkit.org/projects/loginsecurity',selectable=True),width=700),
        ft.Container(ft.Text('Это авторизация с паролем на входе. Позволяет сделать так, чтобы под вашим логином ни кто больше не мог зайти и поиграть. По умолчанию, аккаунт привязан к логину. Так, если на обычном сервере майна бещ пароля, поменять логин на логин дурга, у которого есть алмазы, подождать когда он выйдет с сервера и зайти под его логином, вы считай украли персонажа.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_7/1.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Качаете плагин - это чаще всего просто один файл. Закидываете его в сервере в папку plugins'),width=700),
        ft.Container(ft.Text('Запускаете сервер, подключаетесь, проверяете, что работает. '),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_7/2.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Вот и все, плагин работает. Кстати, после запуска с плагином, в папке плагинов появились другие папки:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_7/3.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Несложно догадаться, что эти папки были созданы плагином авторизации. '),width=700),
        ft.Container(ft.Text('Вот еще один крайне полезный плагин:'),width=700),
        ft.Container(ft.Text('https://www.spigotmc.org/resources/set-home.32748/',selectable=True),width=700),
        ft.Container(ft.Text('Да это же sethome - установка точек дома! Очень полезная штука. Скачай, установи на свой сервер и протестируй.'),width=700),
        ft.Container(ft.Text('Попробуй поставить еще несколько плагинов или модов. Протистируй, чтобы всё работало и можешь переходить к следующему уроку. Как всегда покажи преподу, какие моды установил и что все работает'),width=700),
        ft.Container(ft.Text(''),width=700),
        ft.Container(ft.Text(''),width=700),
        
        
        ])
)
# 8 урок
less_8 = ft.Container(
    ft.Column(controls=[
        ft.Container(ft.Text('Подключаем rcon',text_align='center'),width=700),
        ft.Container(ft.Text('Для начала разберемся, что же такое rcon.'),width=700),
        ft.Container(ft.Text('RCON в Minecraft — это протокол, который позволяет администраторам серверов удалённо выполнять команды Minecraft. Его могут использовать владелец сервера или разработчики, создающие приложения, которые подключаются к серверу Minecraft.'),width=700),
        ft.Container(ft.Text('И вот rcon можно связать с питоном. И управлять дейтсвующим сервером майнкрафта через питон про протоколу rcon. Здорово? Да. В первых 5 уроках вы изучали основы питона. Разбирались с самыми базовыми вещами языка. Теперь фокус работы смещается не столько в программирование, сколько в администрирование и девопс. Вы учитесь работать с серверами, настраивать и администрировать. Вот, чем вы занимаетесь последние уроки. С поднятием сервера мы разобрались. С настройкой сервера (размещение модов и плагинов) вы так же разобрались. Теперь разберемся с тем, как взаимодействовать с уже запущенным сервером. Как его администрировать.'),width=700),
        ft.Container(ft.Text('На самом деле, самое простое взаимодействие с сервером вам уже доступно и без rcon. Через командную строку кносоли окна запущенного сервера.'),width=700),
        ft.Container(ft.Text('Запусти сервер и в косоли снизу введи help'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/1.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Появяться все доступные команды.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/2.gif',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Например, введи say лолка в косноли сервера. Это сообщение от сервера появится в игре'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/3.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Даже обычная консоль даёт нам настолько больше возможностей, нежели это было с библиотекой mcpi! И все эти команды можно миксовать друг с другом, автоматизируя работу через rcon.'),width=700),
        ft.Container(ft.Text('Например, игрок купил у нас привелегию - Опарыш. Это начальный уровень привелгий. Он включает в себя сохранение инвентаря и начальный набор выживальщика - 16 алмазов, железный сет брони, стак хлеба. Пойдёт? Думаю да. Так вот задача - по одной кнопке и небольшой команде выдать привелегию игроку. И проще всего это автоматизировать через rcon. Давайте же разберемся, как он работает.'),width=700),
        ft.Container(ft.Text('Для начала создайте в своей папке папку - lesson_8 и в ней 8.py'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/4.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Далее установим библиотеку для ркона. В консоли пропишите - pip install mcrcon'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/5.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Отлично. Далее нужно включить и настроить ркон в файле конфигурации сервера. В папке сервера открываем в вскоде server.txt.'),width=700),
        ft.Container(ft.Text('Меняем enable-rcon=false на enable-rcon=true'),width=700),
        ft.Container(ft.Text('Далее ищем строку rcon.port=25575. У вас там могут быть другие цифры. Порт нам нужен будет для подключения. Запоминаем его. '),width=700),
        ft.Container(ft.Text('Ну и следом ищем rcon.password. По умолчанию там будет пусто. Это пароль для подключения к ркону. Придумайте его. Например, 11223355 и впишите rcon.password=11223355. Сохраните и закройте файл конфигруации.'),width=700),
        ft.Container(ft.Text('Теперь в файле 8.py напишите следующий код:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/6.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('from mcrcon import MCRcon - Первая строка - это просто подключение библиотеки. '),width=700),
        ft.Container(ft.Text("mc = MCRcon('127.0.0.1','11223355',port=25575) - здесь создаем обект ркон, через который и будем взаимодейтсовать с сервером. В него передается адрес, 127.0.0.1 - это Localhost. Второй параметр - это пароль от rcon, третий - порт rcon."),width=700),
        ft.Container(ft.Text('mc.connect() - далее коннектимся к ркону'),width=700),
        ft.Container(ft.Text('mc.command("say BUGAGA") - и просим выполнить команду - say BUGAGA. С командой say мы только что работали. Пишет в косоль.'),width=700),
        ft.Container(ft.Text('Вот и вся программа. Всё готово. Запуская сервер, заходи в игру и запуская программу.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/7.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('В консоли сервера пройдет сообщение, что Ркон подключился, выполнил команду и отключился. В чате майнкрафта же появится надпись -  [RCON] BUGAGA'),width=700),
        ft.Container(ft.Text('Всё сработало! Отлично. Теперь у нас есть возможность через питон делать вообще что угодно в сервере майнкрафта. Вернемся к первоначальной задаче с выдачей привелегии.'),width=700),
        ft.Container(ft.Text('Сделаем это красиво, через функцию. Для начала разберемся с функциями. Вы с ними еще толком не работали. Я бы хотел объяснить, что такое функции, но просто вставлю 4 картинки с описанием функций, которые я нашел в интернете. Внимательно посмотри каждую и ты поймешь, как работаую функции.'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/8.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/9.jpg',width=700,height=300),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/10.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/11.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Если коротко, то в функцию ты пишешь какой-то код, который исполняется, когда ты вызываешь эту функцию.'),width=700),
        ft.Container(ft.Text('Так вот мы напишем функцию выдачи привелегии по нику игрока. Посмотри на код и прочитай комментарии'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/12.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text('Перепиши код себе. Он пока ничего не делает. Это загатовка. Вот теперь нам поочередно нужно прописать команды, выдающие всякие плюшки:'),width=700),
        ft.Container(ft.Text('1) Команда сохранения инвентаря по нику'),width=700),
        ft.Container(ft.Text('2) Выдть игроку с ником 15 алмазов'),width=700),
        ft.Container(ft.Text('3) Выдать игроку с ником сет брони'),width=700),
        ft.Container(ft.Text('4) Выдать игроку с ником стак хлеба'),width=700),
        ft.Container(ft.Text('Прописать их нужно сюда:'),width=700),
        ft.Container(ft.Image(src='src/pages/content/maincraft_page/img/les_8/13.jpg',width=700),margin=ft.margin.only(left=0)),
        ft.Container(ft.Text("В пустых местах command(''), куда указывает стрелка, нужно вписать какие-то командыЮ соответствующие комментариям. Что это за команды - выясни сам. У тебя есть список команд в консоли. Переводи его. Гугли. Попробуй решить задачу самостоятельно. После выдачи привелегиее напиши еще в чат, что игрок с таким-то ником получил такую-то привелегию."),width=700),
        ft.Container(ft.Text('Выполни задачу и покажи преподу, чтобы он знал, какой ты крутой.'),width=700),
        ft.Container(ft.Text(''),width=700),
        ft.Container(ft.Text(''),width=700),
        ft.Container(ft.Text(''),width=700),
        ft.Container(ft.Text(''),width=700),
        ft.Container(ft.Text(''),width=700),
        
        
        ])
)



less_print = {
    'Урок 1': less_1,
    'Урок 2': less_2,
    'Урок 3': less_3,
    'Урок 4': less_4,
    'Урок 5': less_5,
    'Урок 6': less_6,
    'Урок 7': less_7,
    'Урок 8': less_8,

}